### ISSUE TITLE
Move this project in labs-ci-cd

### ISSUE THREAD

**Issue by sherl0cks** [InfoSec812/openshift-sonarqube#16]
Not sure if we should do this or not, but it may help simplify and consolidate it with our docker builds.

@InfoSec812 @mdanter @oybed thoughts?

**Comment by InfoSec812** [comment]
Agreed... And at the same time, we should start pinning the version of SonarQube for each "release".

**Comment by sherl0cks** [comment]
pinning the version makes sense as well. I spoke with @oybed today and he was good with this change as well. We'll look to get https://github.com/rht-labs/labs-ci-cd/pull/44 merged and then we'll merge in this repo as well.
